# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Prueba de publicación .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "stagging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout a master
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Ejecuta restore para obtener dependencias
      run: dotnet restore
      
    - name: Ejecuta Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Testeando
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish
    
    - name: Instalar ssh-agent y agregar clave con passphrase
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_deploy
          chmod 600 ~/.ssh/id_deploy
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_deploy
    - name: Deploy vía rsync (el más rápido y confiable)
      run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            ./publish/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}/
          
    - name: Restart servicio .NET (systemd) en el servidor
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo systemctl restart kestrel-cerbero.service

    - name: Limpiar clave del agente (seguridad)
      if: always()
      run: |
          ssh-agent -k
          rm -f ~/.ssh/id_deploy
